# Generated by Django 5.1.1 on 2024-09-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='paid_months',
            field=models.JSONField(default=list),
        ),
    ]
