# Generated by Django 5.1.1 on 2024-09-12 19:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_credittransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(default=accounts.models.generate_card_number, max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='cvv',
            field=models.CharField(default=accounts.models.generate_cvv, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='expiration_date',
            field=models.CharField(default=accounts.models.generate_expiration_date, max_length=5),
        ),
    ]
