# Generated by Django 5.1.1 on 2024-09-12 19:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_card_number_profile_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_cvv',
            field=models.CharField(blank=True, default=accounts.models.generate_cvv, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_expiration_date',
            field=models.CharField(blank=True, default=accounts.models.generate_expiration_date, max_length=5, null=True),
        ),
    ]
